version: "1.0"
services:
  todo-app:
    container_name: "todo-app"
    image: ${AUTHOR}/todo-app:${VERSION}
    build: .
    environment:
      DATABASE_URI: sqlite:///data.db
      SECRET_KEY: ${SECRET_KEY}
    ports:
    - target: 5000
      published: 80
